language: node_js

node_js:
  - "8"

script:
  - yarn run build

cache:
  yarn: true

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master